io.github.daggerok.springprops.my-config-props:
  a-string: a string
  a-parent1:
    a-child1:
      a-string-value: a string value 11
      an-another-string-value: an another string value 11
    a-child2:
      a-string-value: a string value 12
      an-another-string-value: an another string value 12
  a-parent2:
    a-child1:
      a-string-value: a string value 21
      an-another-string-value: an another string value 21
    a-child2:
      a-string-value: a string value 22
      an-another-string-value: an another string value 22
